import React,{useEffect,useState} from 'react';
type Listing={root:string;path:string;entries:{name:string;path:string;directory:boolean;size:number|null}[];next_offset:number|null};
export default function MediaBrowser({onChange}:{onChange:(video:string,srt:string)=>void}){
  const [listing,setListing]=useState<Listing|null>(null),[video,setVideo]=useState(''),[srt,setSrt]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function browse(path='',offset=0){setBusy(true);setError('');try{const r=await fetch('/api/media?'+new URLSearchParams({path,offset:String(offset)}));const data=await r.json();if(!r.ok)throw Error(data.detail);setListing(data);}catch(e){setError(String(e));}finally{setBusy(false);}}
  useEffect(()=>{onChange('','');void browse();},[]);
  function choose(path:string){if(path.toLowerCase().endsWith('.srt')){setSrt(path);onChange(video,path);}else{setVideo(path);onChange(path,srt);}}
  return <div className="media-browser">{error&&<p role="alert">{error}</p>}<small>Thư mục trên máy chạy server: {listing?.root}</small><div><button type="button" disabled={busy} onClick={()=>browse()}>Thư mục gốc</button><button type="button" disabled={busy||!listing||listing.path==='.'} onClick={()=>browse(listing!.path.split('/').slice(0,-1).join('/'))}>Lên một cấp</button></div><p>{listing?.path}</p><div className="media-entries">{listing?.entries.map(e=><button type="button" disabled={busy} key={e.path} onClick={()=>e.directory?browse(e.path):choose(e.path)}>{e.directory?'📁 ':''}{e.name}</button>)}{listing?.entries.length===0&&<p>Không có video/SRT hoặc thư mục con.</p>}</div>{listing?.next_offset!==null&&listing&&<button type="button" disabled={busy} onClick={()=>browse(listing.path,listing.next_offset!)}>Trang tiếp</button>}<p>Video: {video||'Chưa chọn'}</p><p>SRT: {srt||'Chưa chọn'}</p></div>;
}
