import React,{useEffect,useRef,useState} from 'react';
import {Mic,Square,Upload,Trash2,Headphones} from 'lucide-react';
type Task={id:string;name:string;text:string;status:string;message:string};
export default function Studio(){
 const [tasks,setTasks]=useState<Task[]>([]),[file,setFile]=useState<File|null>(null),[url,setUrl]=useState(''),[name,setName]=useState(''),[start,setStart]=useState(0),[end,setEnd]=useState(8),[duration,setDuration]=useState(0),[text,setText]=useState('Xin chào, đây là giọng đọc tùy chỉnh của tôi.'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[recording,setRecording]=useState(false);
 const recorder=useRef<MediaRecorder|null>(null), stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),alive=useRef(true);
 const pending=tasks.some(t=>['queued','running'].includes(t.status));
 async function api(path='',method='GET',body?:FormData){const r=await fetch('/api/studio'+path,{method,body});const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data;}
 const refresh=async()=>setTasks(await api());
 useEffect(()=>{alive.current=true;let active=true;const load=()=>api().then(v=>{if(active)setTasks(v);}).catch(e=>{if(active)setError(e.message);});void load();const poll=setInterval(load,1500);return()=>{active=false;alive.current=false;clearInterval(poll);if(timer.current)clearTimeout(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());};},[]);
 useEffect(()=>{if(!file){setUrl('');return;}const next=URL.createObjectURL(file);setUrl(next);return()=>URL.revokeObjectURL(next);},[file]);
 async function act(work:()=>Promise<void>){setBusy(true);setError('');try{await work();await refresh();}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function record(){try{setError('');if(!navigator.mediaDevices?.getUserMedia)throw Error('Thu âm cần localhost hoặc HTTPS và trình duyệt hỗ trợ micro.');const mic=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive.current){mic.getTracks().forEach(t=>t.stop());return;}stream.current=mic;const r=new MediaRecorder(mic);recorder.current=r;const chunks:BlobPart[]=[];r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};r.onstop=()=>{if(timer.current)clearTimeout(timer.current);mic.getTracks().forEach(t=>t.stop());if(alive.current){setRecording(false);setFile(new File(chunks,'microphone.webm',{type:r.mimeType}));}};r.start();setRecording(true);timer.current=setTimeout(()=>{if(r.state==='recording')r.stop();},60000);}catch(e){stream.current?.getTracks().forEach(t=>t.stop());setError(String(e));}}
 return <section className="library-page studio-page"><h1>Phòng thu <small>Clone giọng trên máy</small></h1><p>Nhập hoặc thu mẫu giọng của bạn, chọn đoạn nói rõ từ 3–8 giây, rồi nghe thử trước khi lưu vào thư viện.</p>{error&&<p className="error" role="alert">{error}</p>}
 <form className="studio-form" onSubmit={e=>{e.preventDefault();if(!file)return;void act(async()=>{const data=new FormData();data.append('audio',file);data.append('name',name);data.append('start',String(start));data.append('end',String(end));data.append('text',text);await api('','POST',data);});}}>
 <div className="studio-source"><label className="upload-source"><Upload size={20}/>Chọn mẫu âm thanh<input type="file" accept="audio/*" disabled={recording||busy} onChange={e=>{setFile(e.target.files?.[0]||null);setStart(0);}}/></label><button type="button" disabled={busy} onClick={()=>recording?recorder.current?.stop():void record()}>{recording?<Square size={16}/>:<Mic size={16}/>} {recording?'Dừng thu':'Thu bằng micro'}</button></div>
 {url&&<div className="voice-listener"><strong>{file?.name}</strong><audio controls src={url} onLoadedMetadata={e=>{const d=e.currentTarget.duration;if(Number.isFinite(d)){setDuration(d);setEnd(Math.min(d,8));}else{setDuration(0);}}}/><small>{duration?`Thời lượng: ${duration.toFixed(1)} giây`:'Đặt mốc kết thúc theo thời lượng mẫu đã thu.'}</small></div>}
 <div className="studio-fields"><label>Tên giọng<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>Bắt đầu (giây)<input type="number" min={0} step="0.1" value={start} onChange={e=>setStart(Number(e.target.value))}/></label><label>Kết thúc (giây)<input type="number" min={3} step="0.1" value={end} onChange={e=>setEnd(Number(e.target.value))}/></label></div>
 <label>Câu nghe thử<textarea required maxLength={500} value={text} onChange={e=>setText(e.target.value)}/></label><p className="hint">Mẫu tối đa 50 MB. Tránh nhạc nền, nhiều người nói cùng lúc và âm thanh bị vỡ. Luật phát âm đã lưu được áp dụng cho câu nghe thử.</p><button className="primary" disabled={!file||!name.trim()||busy||pending||recording||end-start<3||end-start>8}><Headphones size={17}/>Tạo giọng và nghe thử</button></form>
 <h2>Giọng trong Phòng thu</h2>{!tasks.length&&<p>Chưa có giọng tùy chỉnh.</p>}{tasks.map(t=><article className="studio-task" key={t.id}><div className="listener-heading"><h3>{t.name}</h3><span className="badge">{({queued:'Đang chờ',running:'Đang tạo',ready:'Chờ lưu',saved:'Đã lưu',failed:'Lỗi',cancelled:'Đã dừng'} as Record<string,string>)[t.status]}</span></div><p role="status">{t.message}</p>{['ready','saved'].includes(t.status)&&<><label>Mẫu giọng đã chọn<audio controls preload="none" src={'/api/studio/'+t.id+'/audio/reference'}/></label><label>Bản đọc thử<audio controls preload="none" src={'/api/studio/'+t.id+'/audio/preview'}/></label></>}
 <div className="library-filters">{['cancelled','failed'].includes(t.status)&&<button disabled={busy||pending} onClick={()=>act(async()=>{await api('/'+t.id+'/retry','POST');})}>Thử lại từ mẫu nguồn</button>}{['queued','running'].includes(t.status)&&<button disabled={busy} onClick={()=>act(async()=>{await api('/'+t.id+'/cancel','POST');})}>Dừng tác vụ</button>}{t.status==='ready'&&<button className="primary" disabled={busy} onClick={()=>act(async()=>{await api('/'+t.id+'/save','POST');})}>Lưu vào thư viện</button>}<button aria-label={'Xóa giọng '+t.name} title="Xóa giọng" disabled={busy||['queued','running'].includes(t.status)} onClick={()=>{if(confirm('Xóa giọng và các mẫu trong Phòng thu? Giọng đang được sử dụng sẽ không thể xóa.'))void act(async()=>{await api('/'+t.id,'DELETE');});}}><Trash2 size={17}/></button></div></article>)}</section>;
}
